services:

  api:
    build:
      context: ./src/api
    container_name: api
    environment:
      - SQL_CONNECTION=Server=db;UID=sa;PWD=${MSSQL_SA_PASSWORD};trusted_connection=false;Persist Security Info=False;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/curl.sh
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_completed_successfully

  app:
    build:
      context: ./src/app
    container_name: app
    environment:
      - SQL_CONNECTION=Server=db;UID=sa;PWD=${MSSQL_SA_PASSWORD};trusted_connection=false;Persist Security Info=False;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy

  ## 1) Bootstrap with scripts
  db:
    build: ./docker/db
    pull_policy: missing
    container_name: db
    hostname: db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT getdate()" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  ## 2) Restore db from backup
  # backup:
  #   build:
  #     context: ./docker/backup
  #     args:
  #       - BACKUP=https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
  #   container_name: backup
  #   hostname: backup
  #   environment:
  #     - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
  #     - ACCEPT_EULA=Y
  #   ports:
  #      - 1432:1433
  #   healthcheck:
  #     test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT getdate()" -b
  #     interval: 10s
  #     timeout: 3s
  #     retries: 10
  #     start_period: 10s
