services:
  app:
    build:
      context: .
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
    ports:
      - 8000:8000
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: migrations
    tty: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    working_dir: /app
    volumes:
      - ./:/app:rw
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -exo pipefail
        printenv
        dotnet new tool-manifest --force
        dotnet tool restore
        dotnet tool install dotnet-ef
        # dotnet add package Microsoft.EntityFrameworkCore.Design
        # dotnet add package Microsoft.EntityFrameworkCore.SQLite
        # dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
        # dotnet add package Microsoft.EntityFrameworkCore.SqlServer
        # dotnet add package Microsoft.EntityFrameworkCore.Tools
        dotnet ef migrations add InitialCreate
        dotnet ef database update -v
        dotnet ef migrations list
