services:
  # curl -H "Authorization: Bearer ${WATCHTOWER_HTTP_API_TOKEN}" localhost:8080/v1/update
  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --debug --http-api-update
      environment:
        - WATCHTOWER_HTTP_API_METRICS=true
        - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      #- WATCHTOWER_ROLLING_RESTART=true
      #- WATCHTOWER_NOTIFICATIONS=msteams
      #- WATCHTOWER_NOTIFICATION_MSTEAMS_USE_LOG_DATA=true
      #- WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL="https://outlook.office.com/webhook/xxxxxxxx@xxxxxxx/IncomingWebhook/yyyyyyyy/zzzzzzzzzz" \
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
      ports:
        - 8080:8080
